force_keyboard_focus = true                                                 # forces keyboard forcus to stay in Walker
close_when_open = true                                                      # close walker when invoking while already opened
selection_wrap = true                                                       # wrap list if at bottom or top
click_to_close = true                                                       # closes walker if clicking outside of the main content area
global_argument_delimiter = "#"                                             # query: firefox#https://benz.dev => part after delimiter will be ignored when querying. this should be the same as in the elephant config
exact_search_prefix = "'"                                                   # disable fuzzy searching
theme = "omarchy-default"                                                   # theme to use
disable_mouse = false                                                       # disable mouse (on input and list only)
additional_theme_location = "~/.local/share/omarchy/default/walker/themes/"

[shell]
anchor_top = true
anchor_bottom = true
anchor_left = true
anchor_right = true

[placeholders]
"default" = { input = " Search...", list = "No Results" } # placeholders for input and empty list, key is the providers name, so f.e. "desktopapplications" or "menus:other"

[keybinds]
close = ["Escape"]
next = ["Down"]
previous = ["Up"]
toggle_exact = ["ctrl e"]
resume_last_query = ["ctrl r"]
quick_activate = []

[providers]
default = [
  "desktopapplications",
  "menus",
  "websearch",
] # providers to be queried by default
empty = ["desktopapplications"] # providers to be queried when query is empty
max_results = 50 # global max results

[providers.sets] # define your own defaults/empty sets of providers
[providers.max_results_provider] # define max results per provider in here

[[providers.prefixes]]
prefix = "/"
provider = "providerlist"

[[providers.prefixes]]
prefix = "."
provider = "files"

[[providers.prefixes]]
prefix = ":"
provider = "symbols"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[[providers.prefixes]]
prefix = "$"
provider = "clipboard"

[providers.actions] # This will be MERGED/OVEWRITTEN with what the user specifies
dmenu = [{ action = "select", default = true, bind = "Return" }]

providerlist = [
  { action = "activate", default = true, bind = "Return", after = "ClearReload" },
]

bluetooth = [
  { action = "find", global = true, bind = "ctrl f", after = "AsyncClearReload" },
  { action = "trust", bind = "ctrl t", after = "AsyncReload" },
  { action = "untrust", bind = "ctrl t", after = "AsyncReload" },
  { action = "pair", bind = "Return", after = "AsyncReload" },
  { action = "remove", bind = "ctrl d", after = "AsyncReload" },
  { action = "connect", bind = "Return", after = "AsyncReload" },
  { action = "disconnect", bind = "Return", after = "AsyncReload" },
]

archlinuxpkgs = [
  { action = "install", bind = "Return", default = true },
  { action = "remove", bind = "Return" },
]

calc = [
  { action = "copy", default = true, bind = "Return" },
  { action = "delete", bind = "ctrl d", after = "AsyncReload" },
  { action = "save", bind = "ctrl s", after = "AsyncClearReload" },
]

websearch = [
  { action = "search", default = true, bind = "Return" },
  { action = "erase_history", label = "clear hist", bind = "ctrl h", after = "Reload" },
]

desktopapplications = [
  { action = "start", default = true, bind = "Return" },
  { action = "start:keep", label = "open+next", bind = "shift Return", after = "KeepOpen" },
  { action = "erase_history", label = "clear hist", bind = "ctrl h", after = "AsyncReload" },
  { action = "pin", bind = "ctrl p", after = "AsyncReload" },
  { action = "unpin", bind = "ctrl p", after = "AsyncReload" },
  { action = "pinup", bind = "ctrl n", after = "AsyncReload" },
  { action = "pindown", bind = "ctrl m", after = "AsyncReload" },
]

files = [
  { action = "open", default = true, bind = "Return" },
  { action = "opendir", label = "open dir", bind = "ctrl Return" },
  { action = "copypath", label = "copy path", bind = "ctrl shift c" },
  { action = "copyfile", label = "copy file", bind = "ctrl c" },
]

todo = [
  { action = "save", default = true, bind = "Return", after = "ClearReload" },
  { action = "delete", bind = "ctrl d", after = "ClearReload" },
  { action = "active", bind = "Return", after = "ClearReload" },
  { action = "inactive", bind = "Return", after = "ClearReload" },
  { action = "done", bind = "ctrl f", after = "ClearReload" },
  { action = "clear", bind = "ctrl x", after = "ClearReload", global = true },
]

clipboard = [
  { action = "copy", default = true, bind = "Return" },
  { action = "clear", global = true, bind = "ctrl x", after = "ClearReload" },
]

symbols = [
  { action = "copy", default = true, bind = "Return" },
]

ssh = [
  { action = "connect", default = true, bind = "Return" },
  { action = "bookmark", bind = "ctrl b", after = "AsyncReload" },
  { action = "bookmark_remove", bind = "ctrl b", after = "AsyncReload" },
  { action = "bookmark_edit", bind = "ctrl e", after = "AsyncReload" },
  { action = "bookmark_up", bind = "ctrl shift Up", after = "AsyncReload" },
  { action = "bookmark_down", bind = "ctrl shift Down", after = "AsyncReload" },
  { action = "bookmark_search", bind = "ctrl f", after = "AsyncReload" },
]

bookmarks = [
  { action = "open", default = true, bind = "Return" },
  { action = "remove", bind = "ctrl d", after = "AsyncReload" },
]

[[providers.bookmarks.entries]]
label = "Omarchy - Github"
keywords = ["omarchy", "github"]
url = "https://github.com/basecamp/omarchy"
icon = ""

[[providers.bookmarks.entries]]
label = "Omarchy Manual"
keywords = ["omarchy"]
url = "https://manuals.omamix.org/2/the-omarchy-manual"
icon = ""
